include:
  - board: nice_nano_v2
    shield: dual_dongle
  - board: nice_nano_v2
    shield: crosses_left
  - board: nice_nano_v2
    shield: crosses_right
  - board: nice_nano_v2
    shield: corne_left
  - board: nice_nano_v2
    shield: corne_right
